version: "3.9"

services:
  backend:
    build: ./backend
    container_name: videfy-backend
    ports:
      - "8000:8000"
    environment:
      - DEEPAI_API_KEY=a42fafad-3212-4e5c-8bad-e2646cefe8e1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: videfy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
