app = "videfy"

[build]
  dockerfile = "Dockerfile"

[env]
  CLOUDINARY_URL="cloudinary://983925166616617:Bfmj-xzKmruB8NDT5cfIhRaHZg8@drfivaaqk"
  DID_API_KEY="Ym90b2xhcHJvc0BnbWFpbC5jb20:UDzhD73UeqWSOcY_hBfiA"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
